### ISSUE TITLE
ImportError: cannot import name CompatibleStreamingHttpResponse

### ISSUE THREAD

**Issue by mmbprog** [umap-project/umap#203]
hi, every body i have problem, after 
    "python manage.py runserver 0.0.0.0:8000"
in terminal show up

/home/mmb/umap/local/lib/python2.7/site-packages/south/modelsinspector.py:20: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  from django.contrib.contenttypes import generic

/home/mmb/umap/local/lib/python2.7/site-packages/south/modelsinspector.py:20: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  from django.contrib.contenttypes import generic

Performing system checks...

System check identified no issues (0 silenced).
August 15, 2015 - 06:10:43
Django version 1.8.3, using settings 'umap.settings.local'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

and after that when i open this link "http://localhost:8000/admin/"

Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/mmb/umap/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/home/mmb/umap/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
    self.load_middleware()
  File "/home/mmb/umap/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 52, in load_middleware
    mw_instance = mw_class()
  File "/home/mmb/umap/local/lib/python2.7/site-packages/django/middleware/locale.py", line 24, in __init__
    for url_pattern in get_resolver(None).url_patterns:
  File "/home/mmb/umap/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/mmb/umap/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/mmb/umap/umap/umap/urls.py", line 9, in <module>
    from leaflet_storage.views import MapShortUrl
  File "/home/mmb/umap/local/lib/python2.7/site-packages/leaflet_storage/views.py", line 12, in <module>
    from django.http import (HttpResponse, HttpResponseForbidden,
ImportError: cannot import name CompatibleStreamingHttpResponse
[15/Aug/2015 06:10:52]"GET /admin HTTP/1.1" 500 59

**Comment by yohanboniface** [comment]
Which version of uMap are you running and which version of Django?

**Comment by mmbprog** [comment]
django 1.8.3
umap last ver from github

**Comment by yohanboniface** [comment]
Humm, are you sure you are up to date with uMap? Can you give me the git hash just to be sure?

**Comment by mmbprog** [comment]
7b5ea8df67132550de33c42e18b74b9a8092fc86

**Comment by mmbprog** [comment]
"7b5ea8df67132550de33c42e18b74b9a8092fc86"

**Comment by yohanboniface** [comment]
Ah, you need to update https://github.com/umap-project/django-leaflet-storage to latest master too
