### ISSUE TITLE
quotes missing from plainto_tsquery

### ISSUE THREAD

**Issue by datendelphin** [umap-project/umap#301]
I get following error: ERROR:  column "xy" does not exist
This error goes away if I issue the same query with the content of plainto_tsquery('xy') in quotes.

I don't know what this function does, if inserting quotes is the proper solution.

**Comment by yohanboniface** [comment]
I can't reproduce.
Can you check:
- umap version
- psycopg2 version
- postgresql version

Also can you paste the full traceback?

**Comment by datendelphin** [comment]
I couldn't get a traceback. I only see the error in the apache error log. I haven't found out how to reproduce. I could post the complete query, but that's probably of not much use.

umap version is c4287bf3
psycopg as mentioned in requirements psycopg2==2.6.1
postgresql is 9.3

**Comment by datendelphin** [comment]
I managed to get a traceback. And my idea of quotes missing seems to be proven wrong. I must have some other (version?) issue

Internal Server Error: /de/search/
Traceback (most recent call last):
  File "/srv/umap.osm.ch/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/umap.osm.ch/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/srv/umap.osm.ch/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/srv/umap.osm.ch/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 158, in get
    context = self.get_context_data(**kwargs)
  File "/srv/umap.osm.ch/umap/umap/views.py", line 155, in get_context_data
    results = self.paginate(results)
  File "/srv/umap.osm.ch/umap/umap/views.py", line 43, in paginate
    qs = paginator.page(1)
  File "/srv/umap.osm.ch/venv/lib/python2.7/site-packages/django/core/paginator.py", line 50, in page
    number = self.validate_number(number)
  File "/srv/umap.osm.ch/venv/lib/python2.7/site-packages/django/core/paginator.py", line 39, in validate_number
    if number > self.num_pages:
  File "/srv/umap.osm.ch/venv/lib/python2.7/site-packages/django/core/paginator.py", line 86, in _get_num_pages
    if self.count == 0 and not self.allow_empty_first_page:
  File "/srv/umap.osm.ch/venv/lib/python2.7/site-packages/django/core/paginator.py", line 72, in _get_count
    self._count = self.object_list.count()
  File "/srv/umap.osm.ch/venv/lib/python2.7/site-packages/django/db/models/query.py", line 318, in count
    return self.query.get_count(using=self.db)
  File "/srv/umap.osm.ch/venv/lib/python2.7/site-packages/django/db/models/sql/query.py", line 466, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/srv/umap.osm.ch/venv/lib/python2.7/site-packages/django/db/models/sql/query.py", line 447, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/srv/umap.osm.ch/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/srv/umap.osm.ch/venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/srv/umap.osm.ch/venv/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/srv/umap.osm.ch/venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: syntax error at or near "xy"
LINE 1: ..." = 1 AND (to_tsvector(name) @@ plainto_tsquery('xy'))...

(xy is not the acutal string, but as it is a production system, I replaced the word with xy)

**Comment by yohanboniface** [comment]
Weird. Psql is not happy, but why.
Can you get the full SQL out?

**Comment by datendelphin** [comment]
here it is:

[Wed Mar 30 08:09:30.666696 2016] [:error] [pid 3204:tid 140173935294208] SELECT "leaflet_storage_map"."id", "leaflet_storage_map"."name", "leaflet_storage_map"."slug", "leaflet_storage_map"."description", "leaflet_storage_map"."center", "leaflet_storage_map"."zoom", "leaflet_storage_map"."locate", "leaflet_storage_map"."licence_id", "leaflet_storage_map"."modified_at", "leaflet_storage_map"."tilelayer_id", "leaflet_storage_map"."owner_id", "leaflet_storage_map"."edit_status", "leaflet_storage_map"."share_status", "leaflet_storage_map"."settings" FROM "leaflet_storage_map" WHERE ("leaflet_storage_map"."share_status" = 1 AND (to_tsvector(name) @@ plainto_tsquery(xy))) ORDER BY "leaflet_storage_map"."modified_at" DESC

The strange thing is: this is from the apache log, and there the quotes are missing from the argument to plainto_tsquery. Not so in the traceback sent by mail from django

**Comment by yohanboniface** [comment]
Can you try with the runserver in a dedicated port?

**Comment by yohanboniface** [comment]
Side note: I suggest uwsgi + nginx to serve python instead of Apache. See https://uwsgi.readthedocs.org/en/latest/tutorials/Django_and_nginx.html for a quick start if needed.

**Comment by datendelphin** [comment]
No quotes printed to console like above, but no mail is sent and the page loads correctly. Now why the error output to console?

**Comment by yohanboniface** [comment]
> Now why the error output to console?

Is it an error, or just the SQL? If it's just the SQL, it's normal: in DEBUG mode, they are printed so we can have a look on them while coding.

**Comment by datendelphin** [comment]
It is not clear. In context it looks like this:

[30/Mar/2016 08:24:08] "GET /en/search?q=xy HTTP/1.1" 301 0
SELECT "leaflet_storage_map"."id", "leaflet_storage_map"."name", "leaflet_storage_map"."slug", "leaflet_storage_map"."description", "leaflet_storage_map"."center", "leaflet_storage_map"."zoom", "leaflet_storage_map"."locate", "leaflet_storage_map"."licence_id", "leaflet_storage_map"."modified_at", "leaflet_storage_map"."tilelayer_id", "leaflet_storage_map"."owner_id", "leaflet_storage_map"."edit_status", "leaflet_storage_map"."share_status", "leaflet_storage_map"."settings" FROM "leaflet_storage_map" WHERE ("leaflet_storage_map"."share_status" = 1 AND (to_tsvector(name) @@ plainto_tsquery(xy))) ORDER BY "leaflet_storage_map"."modified_at" DESC
[30/Mar/2016 08:24:09] "GET /en/search/?q=xy HTTP/1.1" 200 4095

DEBUG = False in the settings

**Comment by yohanboniface** [comment]
Humm, ok, a print was left in the code ;) 
So that's not an error, and then I don't see why when running through Apache it becomes an error. :s
Can you try running with gunicorn in a dedicated port, in the scope of mitigating the context of the bug?

**Comment by datendelphin** [comment]
ah good. I think I'll just remove the print line.

Why should I run gunicorn? To find out why apache makes an error from the console output?

**Comment by yohanboniface** [comment]
> Why should I run gunicorn? To find out why apache makes an error from the console output?

Trying to see in which context(s) you can reproduce the error, to help diagnosing remotely.

**Comment by datendelphin** [comment]
Ah I think I was a bit unclear. There is no real Error, not in Apache as well. I just saw it in the error log and got confused, because at first I couldn't reproduce it.
Tinkering with quotes gave me the backtrace and with it a clue where the error came from (search)
So now I removed the printf the log is relieved and my confusion has gone away :) thanks
