### ISSUE TITLE
Search Error

### ISSUE THREAD

**Issue by kleper** [umap-project/umap#591]
I have this error when i do a search:

Internal Server Error: /es/search/
Traceback (most recent call last):
  File "/srv/umap/venv/lib/python3.6/site-packages/django/core/paginator.py", line 34, in validate_number
    number = int(number)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/umap/venv/lib/python3.6/site-packages/umap/views.py", line 48, in paginate
    qs = paginator.page(page)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/core/paginator.py", line 50, in page
    number = self.validate_number(number)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/core/paginator.py", line 36, in validate_number
    raise PageNotAnInteger('That page number is not an integer')
django.core.paginator.PageNotAnInteger: That page number is not an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: function unaccent(character varying) does not exist
LINE 1: ..._storage_map"."share_status" = 1 AND (to_tsvector(unaccent(n...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/umap/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 155, in get
    context = self.get_context_data(**kwargs)
  File "/srv/umap/venv/lib/python3.6/site-packages/umap/views.py", line 162, in get_context_data
    results = self.paginate(results)
  File "/srv/umap/venv/lib/python3.6/site-packages/umap/views.py", line 51, in paginate
    qs = paginator.page(1)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/core/paginator.py", line 50, in page
    number = self.validate_number(number)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/core/paginator.py", line 39, in validate_number
    if number > self.num_pages:
  File "/srv/umap/venv/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/core/paginator.py", line 84, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
  File "/srv/umap/venv/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/core/paginator.py", line 72, in count
    return self.object_list.count()
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/query.py", line 369, in count
    return self.query.get_count(using=self.db)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/sql/query.py", line 476, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/sql/query.py", line 457, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: function unaccent(character varying) does not exist
LINE 1: ..._storage_map"."share_status" = 1 AND (to_tsvector(unaccent(n...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

**Comment by yohanboniface** [comment]
Have you installed `unaccent` extension?

    psql -d umap -c 'CREATE EXTENSION unaccent'

Or you can disable `unaccent` in umap settings:

    UMAP_USE_UNACCENT = False

**Comment by kleper** [comment]
Thanks, i solve the problem with that command.
