### ISSUE TITLE
UMAP Colombia migration

### ISSUE THREAD

**Issue by kleper** [umap-project/umap#592]
Hello,

I have two instances of UMAP:
https://umapold.openstreetmap.co with the old version of UMAP, I think the 0.7 or a little older since it has more than 4 years and was never updated.
I want to migrate the data to the current version 0.8.3 that I have in https://umap.openstreetmap.co.
Try to pass the database from the old version to the new one, but when I executed the migrations script I could not do it, I do not know if they have any recommendations that they can give me to achieve it?

Thank you.

**Comment by yohanboniface** [comment]
> but when I executed the migrations script I could not do it

Can you be a bit more explicit (sharing the command line, the console output…, or a screenshot with the error) ?

Also note that I'm in the process of freezing a 1.0 version, see #583.

**Comment by kleper** [comment]
At this time I put in for users to migrate their maps manually. I think I prefer to wait for version 1.0 and migrate from version 0.8.3

That the attempted migration to version 0.8.3 old I did two weeks ago and do not save logs but will make a new attempt at night and copy the logs for what it's worth.
Thank you.

**Comment by kleper** [comment]
This is the error:
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, leaflet_storage, sessions, sites, social_django, umap
Running migrations:
  No migrations to apply.
Traceback (most recent call last):
  File "/srv/umap/venv/lib/python3.6/site-packages/django/contrib/contenttypes/models.py", line 52, in get_for_model
    ct = self.get(app_label=opts.app_label, model=opts.model_name)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
__fake__.DoesNotExist: ContentType matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/query.py", line 473, in get_or_create
    return self.get(**lookup), False
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
__fake__.DoesNotExist: ContentType matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.IntegrityError: null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (18, null, social_django, association).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/umap/venv/bin/umap", line 11, in <module>
    sys.exit(main())
  File "/srv/umap/venv/lib/python3.6/site-packages/umap/bin/__init__.py", line 12, in main
    management.execute_from_command_line()
  File "/srv/umap/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/srv/umap/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 224, in handle
    self.verbosity, self.interactive, connection.alias, apps=post_migrate_apps, plan=plan,
  File "/srv/umap/venv/lib/python3.6/site-packages/django/core/management/sql.py", line 53, in emit_post_migrate_signal
    **kwargs
  File "/srv/umap/venv/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 191, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/contrib/auth/management/__init__.py", line 63, in create_permissions
    ctype = ContentType.objects.db_manager(using).get_for_model(klass)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/contrib/contenttypes/models.py", line 58, in get_for_model
    model=opts.model_name,
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/query.py", line 475, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/query.py", line 513, in _create_object_from_params
    six.reraise(*exc_info)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/utils/six.py", line 686, in reraise
    raise value
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/query.py", line 505, in _create_object_from_params
    obj = self.create(**params)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/query.py", line 399, in create
    obj.save(force_insert=True, using=self.db)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
    cursor.execute(sql, params)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (18, null, social_django, association).

**Comment by yohanboniface** [comment]
You may have fallen in that trap: https://github.com/omab/python-social-auth/blob/master/MIGRATING_TO_SOCIAL.md#migrations

**Comment by kleper** [comment]
In this issue it is somewhat different, what I did was the following, install a completely new version of UMAP, take the database of the old version and clone it into a new database, configure my new installation to use this base of data and I ran the migration command. And I get the error that I put behind.

**Comment by yohanboniface** [comment]
Somewhat different, but somewhat similar too: you are running a newer version of the social-auth code with a database made with an older version.

**Comment by kleper** [comment]
Yes, although it is the latest version of the code, use these instructions https://umap-project.readthedocs.io/en/latest/ubuntu/ to have version 0.8.3 of UMAP
In this new installation I can not find the manage.py file, do you recommend downloading the code and installing it from there?

**Comment by yohanboniface** [comment]
> In this new installation I can not find the manage.py file

If you have installed the project with `pip install` (which is the recommended way to do so), you should use `umap` instead of `manage.py`, so for example `manage.py migrate` should be `umap migrate`.

**Comment by kleper** [comment]
Yes i doing that, and have the same error

(venv) umap@TM3:/srv/umap$ umap migrate

Operations to perform:
  Apply all migrations: admin, auth, contenttypes, leaflet_storage, sessions, sites, social_django, umap
Running migrations:
  No migrations to apply.
Traceback (most recent call last):
  File "/srv/umap/venv/lib/python3.6/site-packages/django/contrib/contenttypes/models.py", line 52, in get_for_model
    ct = self.get(app_label=opts.app_label, model=opts.model_name)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
__fake__.DoesNotExist: ContentType matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/query.py", line 473, in get_or_create
    return self.get(**lookup), False
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
__fake__.DoesNotExist: ContentType matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.IntegrityError: null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (20, null, social_django, association).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/umap/venv/bin/umap", line 11, in <module>
    sys.exit(main())
  File "/srv/umap/venv/lib/python3.6/site-packages/umap/bin/__init__.py", line 12, in main
    management.execute_from_command_line()
  File "/srv/umap/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/srv/umap/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 224, in handle
    self.verbosity, self.interactive, connection.alias, apps=post_migrate_apps, plan=plan,
  File "/srv/umap/venv/lib/python3.6/site-packages/django/core/management/sql.py", line 53, in emit_post_migrate_signal
    **kwargs
  File "/srv/umap/venv/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 191, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/contrib/auth/management/__init__.py", line 63, in create_permissions
    ctype = ContentType.objects.db_manager(using).get_for_model(klass)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/contrib/contenttypes/models.py", line 58, in get_for_model
    model=opts.model_name,
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/query.py", line 475, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/query.py", line 513, in _create_object_from_params
    six.reraise(*exc_info)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/utils/six.py", line 686, in reraise
    raise value
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/query.py", line 505, in _create_object_from_params
    obj = self.create(**params)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/query.py", line 399, in create
    obj.save(force_insert=True, using=self.db)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
    cursor.execute(sql, params)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/srv/umap/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (20, null, social_django, association).

**Comment by kleper** [comment]
I made other tests I get this error, apparently the database of my old umap has a lot of differences with the new database and when the migrate runs it does not have a script that does the field
"CommandError: Unable to serialize database: WITHIN GROUP is required for ordered-set aggregate rank
LINE 1: ... "," leaflet_storage_datalayer "." Display_on_load "," leaflet_s ...

This happens when I start the umap ignoring the error when executing umap migrate

**Comment by yohanboniface** [comment]
Have you tried the steps described in https://github.com/omab/python-social-auth/blob/master/MIGRATING_TO_SOCIAL.md#migrations ?

Also, instead of doing a full migrate, you can do it app by app to narrow down which one is failing; `umap migrate admin`, then `umap migrate auth` and so on, from this line:

>  Apply all migrations: admin, auth, contenttypes, leaflet_storage, sessions, sites, social_django, umap

**Comment by kleper** [comment]
If I tried and I did step by step the link that you sent me and try one by one the migrations and the same error that I copied.
