### ISSUE TITLE
install

### ISSUE THREAD

**Issue by drunkod** [umap-project/umap#694]
(venv) root@node70884-python-env-2514619:~# umap        
Traceback (most recent call last):
  File "/srv/umap/venv/bin/umap", line 10, in <module>
    sys.exit(main())
  File "/srv/umap/venv/local/lib/python3.6/site-packages/umap/bin/__init__.py", line 12, in main
    management.execute_from_command_line()
  File "/srv/umap/venv/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/srv/umap/venv/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/srv/umap/venv/local/lib/python3.6/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/srv/umap/venv/local/lib/python3.6/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/srv/umap/venv/local/lib/python3.6/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/srv/umap/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/umap/venv/local/lib/python3.6/site-packages/umap/settings/__init__.py", line 29, in <module>
    exec(compile(config_file.read(), path, 'exec'), d.__dict__)
  File "/srv/umap/venv/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1223: ordinal not in range(128)

**Comment by yohanboniface** [comment]
Unicode error, can you share your local settings (but removing any password or secret_key before, of course)?

**Comment by drunkod** [comment]
The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
root@node70890-python35-env-8836281:~# locale
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=
root@node70890-python35-env-8836281:~# locale -a
C
C.UTF-8
POSIX

**Comment by yohanboniface** [comment]
> can you share your local settings (but removing any password or secret_key before, of course)?

The `/etc/umap/umap.conf` file I meant

**Comment by Binnette** [comment]
No response from user. @drunkod, feel free to reopen this issue if needed.
